-- MySQL Script generated by MySQL Workbench
-- 12/29/14 17:55:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gbook_iglesiaquepos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gbook_iglesiaquepos` ;

-- -----------------------------------------------------
-- Schema gbook_iglesiaquepos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gbook_iglesiaquepos` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `gbook_iglesiaquepos` ;

-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`type_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`type_user` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`type_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`iglesias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`iglesias` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`iglesias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(9) NOT NULL,
  `misions_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`users` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(85) NOT NULL,
  `last` VARCHAR(65) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` TEXT(0) NOT NULL,
  `remember_token` TEXT(0) NULL,
  `type_user_id` INT NOT NULL,
  `iglesias_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_type_user1`
    FOREIGN KEY (`type_user_id`)
    REFERENCES `gbook_iglesiaquepos`.`type_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_iglesias1`
    FOREIGN KEY (`iglesias_id`)
    REFERENCES `gbook_iglesiaquepos`.`iglesias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_type_user1_idx` ON `gbook_iglesiaquepos`.`users` (`type_user_id` ASC);

CREATE INDEX `fk_users_iglesias1_idx` ON `gbook_iglesiaquepos`.`users` (`iglesias_id` ASC);


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`miembros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`miembros` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`miembros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(85) NOT NULL,
  `last` VARCHAR(85) NOT NULL,
  `date_bautizmo` DATE NOT NULL,
  `date_nacimiento` DATE NOT NULL,
  `phone` VARCHAR(13) NOT NULL,
  `celular` VARCHAR(13) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `iglesias_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_miembros_iglesias1`
    FOREIGN KEY (`iglesias_id`)
    REFERENCES `gbook_iglesiaquepos`.`iglesias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_miembros_iglesias1_idx` ON `gbook_iglesiaquepos`.`miembros` (`iglesias_id` ASC);


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`tipos_fijos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`tipos_fijos` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`tipos_fijos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`tipos_variales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`tipos_variales` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`tipos_variales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`ingresos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`ingresos` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`ingresos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num_sobre` INT NOT NULL,
  `num_control` INT NOT NULL,
  `date` DATE NOT NULL,
  `monto` DECIMAL(20,2) NOT NULL,
  `miembros_id` INT NOT NULL,
  `tipos_fijos_id` INT NOT NULL,
  `tipos_variales_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ingresos_tipos_fijos1`
    FOREIGN KEY (`tipos_fijos_id`)
    REFERENCES `gbook_iglesiaquepos`.`tipos_fijos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingresos_tipos_variales1`
    FOREIGN KEY (`tipos_variales_id`)
    REFERENCES `gbook_iglesiaquepos`.`tipos_variales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingresos_miembros1`
    FOREIGN KEY (`miembros_id`)
    REFERENCES `gbook_iglesiaquepos`.`miembros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ingresos_tipos_fijos1_idx` ON `gbook_iglesiaquepos`.`ingresos` (`tipos_fijos_id` ASC);

CREATE INDEX `fk_ingresos_tipos_variales1_idx` ON `gbook_iglesiaquepos`.`ingresos` (`tipos_variales_id` ASC);

CREATE INDEX `fk_ingresos_miembros1_idx` ON `gbook_iglesiaquepos`.`ingresos` (`miembros_id` ASC);


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`departamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`departamentos` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`departamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `saldo` DECIMAL(20,2) NOT NULL,
  `iglesias_id` INT NOT NULL,
  `iglesias_users_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_departamentos_iglesias1`
    FOREIGN KEY (`iglesias_id`)
    REFERENCES `gbook_iglesiaquepos`.`iglesias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_departamentos_iglesias1_idx` ON `gbook_iglesiaquepos`.`departamentos` (`iglesias_id` ASC, `iglesias_users_id` ASC);


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`gastos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`gastos` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`gastos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num_factura` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `datefactura` DATE NOT NULL,
  `monto` DECIMAL(20,2) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `departamentos_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_gastos_departamentos1`
    FOREIGN KEY (`departamentos_id`)
    REFERENCES `gbook_iglesiaquepos`.`departamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_gastos_departamentos1_idx` ON `gbook_iglesiaquepos`.`gastos` (`departamentos_id` ASC);


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`cheques`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`cheques` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`cheques` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `date` DATE NOT NULL,
  `datalle` VARCHAR(255) NOT NULL,
  `monto` DECIMAL(20,2) NOT NULL,
  `tipos_fijos_id` INT NOT NULL,
  `tipos_variales_id` INT NOT NULL,
  `departamentos_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cheques_tipos_fijos1`
    FOREIGN KEY (`tipos_fijos_id`)
    REFERENCES `gbook_iglesiaquepos`.`tipos_fijos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cheques_tipos_variales1`
    FOREIGN KEY (`tipos_variales_id`)
    REFERENCES `gbook_iglesiaquepos`.`tipos_variales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cheques_departamentos1`
    FOREIGN KEY (`departamentos_id`)
    REFERENCES `gbook_iglesiaquepos`.`departamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cheques_tipos_fijos1_idx` ON `gbook_iglesiaquepos`.`cheques` (`tipos_fijos_id` ASC);

CREATE INDEX `fk_cheques_tipos_variales1_idx` ON `gbook_iglesiaquepos`.`cheques` (`tipos_variales_id` ASC);

CREATE INDEX `fk_cheques_departamentos1_idx` ON `gbook_iglesiaquepos`.`cheques` (`departamentos_id` ASC);

USE `gbook_iglesiaquepos` ;

-- -----------------------------------------------------
-- Placeholder table for view `gbook_iglesiaquepos`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`view1` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `gbook_iglesiaquepos`.`view2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`view2` (`id` INT);

-- -----------------------------------------------------
-- View `gbook_iglesiaquepos`.`view1`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `gbook_iglesiaquepos`.`view1` ;
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`view1`;
USE `gbook_iglesiaquepos`;


-- -----------------------------------------------------
-- View `gbook_iglesiaquepos`.`view2`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `gbook_iglesiaquepos`.`view2` ;
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`view2`;
USE `gbook_iglesiaquepos`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
