-- MySQL Script generated by MySQL Workbench
-- 12/22/14 14:19:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gbook_iglesiaquepos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gbook_iglesiaquepos` ;

-- -----------------------------------------------------
-- Schema gbook_iglesiaquepos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gbook_iglesiaquepos` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `gbook_iglesiaquepos` ;

-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`users` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(85) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` TEXT(0) NOT NULL,
  `user_type` INT NOT NULL,
  `remember_token` TEXT(0) NULL,
  `created_at` TIMESTAMP(6) NOT NULL,
  `updated_at` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`Divisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`Divisions` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`Divisions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Divisions_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `gbook_iglesiaquepos`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Divisions_users1_idx` ON `gbook_iglesiaquepos`.`Divisions` (`users_id` ASC);


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`unions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`unions` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`unions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  `created_at` TIMESTAMP(6) NOT NULL,
  `updated_at` TIMESTAMP(6) NOT NULL,
  `Divisions_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  CONSTRAINT `fk_unions_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `gbook_iglesiaquepos`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_unions_Divisions1`
    FOREIGN KEY (`Divisions_id`)
    REFERENCES `gbook_iglesiaquepos`.`Divisions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_unions_users1_idx` ON `gbook_iglesiaquepos`.`unions` (`users_id` ASC);

CREATE INDEX `fk_unions_Divisions1_idx` ON `gbook_iglesiaquepos`.`unions` (`Divisions_id` ASC);


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`misions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`misions` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`misions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `unions_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `created_at` TIMESTAMP(6) NOT NULL,
  `updated_at` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  CONSTRAINT `fk_misions_unions1`
    FOREIGN KEY (`unions_id`)
    REFERENCES `gbook_iglesiaquepos`.`unions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_misions_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `gbook_iglesiaquepos`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_misions_unions1_idx` ON `gbook_iglesiaquepos`.`misions` (`unions_id` ASC);

CREATE INDEX `fk_misions_users1_idx` ON `gbook_iglesiaquepos`.`misions` (`users_id` ASC);


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`iglesias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`iglesias` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`iglesias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  `misions_id` INT NOT NULL,
  `created_at` TIMESTAMP(6) NOT NULL,
  `updated_at` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  CONSTRAINT `fk_iglesias_misions`
    FOREIGN KEY (`misions_id`)
    REFERENCES `gbook_iglesiaquepos`.`misions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_iglesias_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `gbook_iglesiaquepos`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE INDEX `fk_iglesias_misions_idx` ON `gbook_iglesiaquepos`.`iglesias` (`misions_id` ASC);

CREATE INDEX `fk_iglesias_users1_idx` ON `gbook_iglesiaquepos`.`iglesias` (`users_id` ASC);


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`miembros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`miembros` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`miembros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(100) NOT NULL,
  `date_bautizmo` DATE NOT NULL,
  `date_nacimiento` DATE NOT NULL,
  `phone` VARCHAR(13) NOT NULL,
  `celular` VARCHAR(13) NOT NULL,
  `created_at` TIMESTAMP(6) NOT NULL,
  `updated_at` TIMESTAMP(6) NOT NULL,
  `iglesias_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_miembros_iglesias1`
    FOREIGN KEY (`iglesias_id`)
    REFERENCES `gbook_iglesiaquepos`.`iglesias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_miembros_iglesias1_idx` ON `gbook_iglesiaquepos`.`miembros` (`iglesias_id` ASC);


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`tipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`tipos` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`tipos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `created_at` TIMESTAMP(6) NOT NULL,
  `updated_at` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`ingresos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`ingresos` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`ingresos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num_sobre` INT NOT NULL,
  `num_control` INT NOT NULL,
  `date` DATE NOT NULL,
  `monto` DECIMAL(20,2) NOT NULL,
  `tipos_id` INT NOT NULL,
  `iglesias_id` INT NOT NULL,
  `iglesias_users_id` INT NOT NULL,
  `created_at` TIMESTAMP(6) NOT NULL,
  `updated_at` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ingresos_tipos1`
    FOREIGN KEY (`tipos_id`)
    REFERENCES `gbook_iglesiaquepos`.`tipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingresos_iglesias1`
    FOREIGN KEY (`iglesias_id` , `iglesias_users_id`)
    REFERENCES `gbook_iglesiaquepos`.`iglesias` (`id` , `users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ingresos_tipos1_idx` ON `gbook_iglesiaquepos`.`ingresos` (`tipos_id` ASC);

CREATE INDEX `fk_ingresos_iglesias1_idx` ON `gbook_iglesiaquepos`.`ingresos` (`iglesias_id` ASC, `iglesias_users_id` ASC);


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`departamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`departamentos` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`departamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP(6) NOT NULL,
  `updated_at` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`gastos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`gastos` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`gastos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num_factura` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `datefactura` DATE NOT NULL,
  `monto` DECIMAL(20,2) NOT NULL,
  `descripcion` TEXT(0) NOT NULL,
  `departamentos_id` INT NOT NULL,
  `iglesias_id` INT NOT NULL,
  `iglesias_users_id` INT NOT NULL,
  `created_at` TIMESTAMP(6) NOT NULL,
  `updated_at` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_gastos_departamentos1`
    FOREIGN KEY (`departamentos_id`)
    REFERENCES `gbook_iglesiaquepos`.`departamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gastos_iglesias1`
    FOREIGN KEY (`iglesias_id` , `iglesias_users_id`)
    REFERENCES `gbook_iglesiaquepos`.`iglesias` (`id` , `users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_gastos_departamentos1_idx` ON `gbook_iglesiaquepos`.`gastos` (`departamentos_id` ASC);

CREATE INDEX `fk_gastos_iglesias1_idx` ON `gbook_iglesiaquepos`.`gastos` (`iglesias_id` ASC, `iglesias_users_id` ASC);


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`miembros_has_ingresos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`miembros_has_ingresos` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`miembros_has_ingresos` (
  `miembros_id` INT NOT NULL,
  `ingresos_id` INT NOT NULL,
  PRIMARY KEY (`miembros_id`, `ingresos_id`),
  CONSTRAINT `fk_miembros_has_ingresos_miembros1`
    FOREIGN KEY (`miembros_id`)
    REFERENCES `gbook_iglesiaquepos`.`miembros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_miembros_has_ingresos_ingresos1`
    FOREIGN KEY (`ingresos_id`)
    REFERENCES `gbook_iglesiaquepos`.`ingresos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_miembros_has_ingresos_ingresos1_idx` ON `gbook_iglesiaquepos`.`miembros_has_ingresos` (`ingresos_id` ASC);

CREATE INDEX `fk_miembros_has_ingresos_miembros1_idx` ON `gbook_iglesiaquepos`.`miembros_has_ingresos` (`miembros_id` ASC);


-- -----------------------------------------------------
-- Table `gbook_iglesiaquepos`.`cheques`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`cheques` ;

CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`cheques` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `date` DATE NOT NULL,
  `datalle` VARCHAR(255) NOT NULL,
  `monto` DECIMAL(20,2) NOT NULL,
  `created_at` TIMESTAMP(6) NOT NULL,
  `updated_at` TIMESTAMP(6) NOT NULL,
  `tipos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cheques_tipos1`
    FOREIGN KEY (`tipos_id`)
    REFERENCES `gbook_iglesiaquepos`.`tipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cheques_tipos1_idx` ON `gbook_iglesiaquepos`.`cheques` (`tipos_id` ASC);

USE `gbook_iglesiaquepos` ;

-- -----------------------------------------------------
-- Placeholder table for view `gbook_iglesiaquepos`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`view1` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `gbook_iglesiaquepos`.`view2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gbook_iglesiaquepos`.`view2` (`id` INT);

-- -----------------------------------------------------
-- View `gbook_iglesiaquepos`.`view1`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `gbook_iglesiaquepos`.`view1` ;
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`view1`;
USE `gbook_iglesiaquepos`;


-- -----------------------------------------------------
-- View `gbook_iglesiaquepos`.`view2`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `gbook_iglesiaquepos`.`view2` ;
DROP TABLE IF EXISTS `gbook_iglesiaquepos`.`view2`;
USE `gbook_iglesiaquepos`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
